### ISSUE TITLE
Use autowiring on loaders with parents

### ISSUE THREAD

**Issue by vincentchalamon** [coopTilleuls/CoopTilleulsMigrationBundle#3]
It's impossible to use autowiring with `parent` keyword:
```yml
services:
    App\Loader\UserLoader:
        class: App\Loader\UserLoader
        parent: coop_tilleuls_migration.loader.abstract
        autowire: false
        autoconfigure: false
        public: false
        tags:
            - { name: coop_tilleuls_migration.loader, alias: user }
```
